-- Plays a random uwu when the player lands a critical hit or heal, and an
-- angry uwu / ara ara when the player gets crit or loses a big chunk of health
-- in one hit. Sound lists come from Sounds.lua (and SoundsLocal.lua for clips
-- that stay on this machine); WoW can't list files, so they are generated by
-- tools/build_sounds.py.

local ADDON_NAME, ns = ...;

local DEFAULTS = {
	enabled = true,
	crit = true,
	hurt = true,
	small = true,
	critCooldown = 1.5,
	hurtCooldown = 3,
	hurtPercent = 25,
	volume = 60,
	bubbles = true,
	bubbleX = 40,
	bubbleY = 140,
};

-- PlaySoundFile has no volume argument, so tools/build_sounds.py renders every
-- clip once per level and the sound lists hold a %d for the level.
local VOLUME_STEP = 20;

-- Small uwus fill the gaps between full ones but must not stack into noise
-- when an AoE crits ten targets in the same frame.
local SMALL_GAP = 0.2;
local CHANNEL = "Master";

local db;
local lastCrit, lastSmall, lastHurt = 0, 0, 0;

-- Shuffle bag per pool: every clip plays once before any clip repeats,
-- and the last clip of a round never opens the next one.
local bags = {};

local function Pool(kind)
	local pool = {};
	for _, list in ipairs(ns.soundLists or {}) do
		for _, path in ipairs(list[kind] or {}) do
			pool[#pool + 1] = path;
		end
	end
	return pool;
end

local function NextSound(kind)
	local bag = bags[kind];
	if not bag or bag.pos > #bag then
		local pool = Pool(kind);
		if #pool == 0 then
			return nil;
		end
		for i = #pool, 2, -1 do
			local j = math.random(i);
			pool[i], pool[j] = pool[j], pool[i];
		end
		local previous = bag and bag[#bag];
		if #pool > 1 and pool[1] == previous then
			pool[1], pool[#pool] = pool[#pool], pool[1];
		end
		pool.pos = 1;
		bags[kind] = pool;
		bag = pool;
	end
	local path = bag[bag.pos];
	bag.pos = bag.pos + 1;
	return path;
end

local function PlayPath(kind, path)
	if db.bubbles then
		ns.ShowBubble(kind, db.bubbleX, db.bubbleY);
	end
	if path then
		PlaySoundFile(path:format(db.volume), CHANNEL);
		return true;
	end
	return false;
end

local function Play(kind)
	return PlayPath(kind, NextSound(kind));
end

local function OnOwnCrit()
	if not db.crit then
		return;
	end
	local now = GetTime();
	if now - lastCrit >= db.critCooldown then
		lastCrit = now;
		lastSmall = now;
		Play("crit");
	elseif db.small and now - lastSmall >= SMALL_GAP then
		lastSmall = now;
		Play("small");
	end
end

local function OnHurt()
	if not db.hurt then
		return;
	end
	local now = GetTime();
	if now - lastHurt >= db.hurtCooldown then
		lastHurt = now;
		-- Keeps a crit uwu from talking over the hurt sound right away.
		lastCrit = now;
		Play("hurt");
	end
end

-- The combat log is off limits to addons on this client (registering
-- COMBAT_LOG_EVENT_UNFILTERED is a forbidden action), so this uses UNIT_COMBAT,
-- the event behind the hit numbers on the unit frames, plus COMBAT_TEXT_UPDATE,
-- which names crits on the player as *_CRIT. Neither has a source; see
-- WasMine below for how the player's own crits are told apart.
--
-- A killing blow comes without the CRITICAL flag even when it crit. Mobs often
-- die after a few hits, so most crits are killing blows. For those, a hit
-- clearly above the biggest recent plain hit of its damage school counts as a
-- crit. Comparing with the biggest (not the typical) hit keeps a strong ability
-- from passing as a crit auto attack; a crit auto attack that kills is missed
-- instead. Crits do double damage, spells 1.5x. Kept across fights.
local HISTORY = 15;
local MIN_HISTORY = 3;
local CRIT_FACTOR = 1.3;
local history = {};

local function Remember(school, amount)
	local list = history[school];
	if not list then
		list = {};
		history[school] = list;
	end
	list[#list + 1] = amount;
	if #list > HISTORY then
		table.remove(list, 1);
	end
end

local function LooksLikeCrit(school, amount)
	local list = history[school];
	if not list or #list < MIN_HISTORY then
		return false;
	end
	local biggest = math.max(unpack(list));
	return biggest > 0 and amount >= biggest * CRIT_FACTOR;
end

local debugMode = false;

local function Debug(...)
	if debugMode then
		print("|cffff80c0UwU|r", ...);
	end
end

-- UNIT_COMBAT has no source, so a crit counts as the player's own only when
-- it lines up with something the player did: a melee swing or a spell, auto
-- shot or channel that may still be on its way. PLAYER_SWING fires when the
-- swing starts, the hit shows up about half a second later (server round
-- trip), and auto attacks only ever hit the target, so swings only vouch for
-- crits on the target. Crits of other players outside such a window are
-- dropped; one landing inside it still slips through. Periodic ticks (DoTs,
-- HoTs) and pet hits come without an action of the player and are missed.
local SWING_SLACK = 0.15;
local SWING_WINDOW = 1;
local CAST_WINDOW = 1.5;
local lastSwing, lastCast = -100, -100;
local channeling = false;

local function WasMine(time, onTarget)
	return channeling
		or (time - lastCast >= -SWING_SLACK and time - lastCast <= CAST_WINDOW)
		or (onTarget and time - lastSwing >= -SWING_SLACK and time - lastSwing <= SWING_WINDOW);
end

local function OnCritIfMine(time, onTarget)
	time = time or GetTime();
	if WasMine(time, onTarget) then
		OnOwnCrit();
		return;
	end
	-- The cast event may arrive a moment after the hit it belongs to.
	C_Timer.After(SWING_SLACK, function()
		if WasMine(time, onTarget) then
			OnOwnCrit();
		else
			Debug(("crit ignored, not mine (%s, swing %+.2f s, cast %+.2f s)"):format(
				onTarget and "target" or "not target", lastSwing - time, lastCast - time));
		end
	end);
end

-- Enum.PlayerSwingType.Ranged; a missing Enum table would be a hidden Lua error
-- that silently drops every melee crit.
local RANGED_SWING = 2;

local function OnSwing(swingType)
	Debug("swing", swingType);
	if swingType == RANGED_SWING then
		-- The shot still has to fly.
		lastCast = GetTime();
	else
		lastSwing = GetTime();
	end
end

local CRIT_TEXT = {
	DAMAGE_CRIT = "hurt",
	SPELL_DAMAGE_CRIT = "hurt",
	HEAL_CRIT = "crit",
	PERIODIC_HEAL_CRIT = "crit",
};

local function OnCombatText(textType)
	local kind = CRIT_TEXT[textType];
	if kind then
		Debug("text", textType, kind);
	end
	if kind == "hurt" then
		OnHurt();
	elseif kind == "crit" then
		OnCritIfMine();
	end
end

-- The last plain hit on the target, until it is known whether it killed.
local KILL_WINDOW = 0.3;
local pendingHit;

local function OnKillingBlow(how)
	local hit = pendingHit;
	pendingHit = nil;
	if not hit then
		return;
	end
	local crit = LooksLikeCrit(hit.school, hit.amount);
	Debug("kill", hit.amount, "school " .. tostring(hit.school), how, crit and "CRIT" or "");
	if crit then
		OnCritIfMine(hit.time, true);
	end
end

-- Mobs other than the target (Swipe, Cleave, multi-dotting) are only seen
-- through their nameplates, so only while enemy nameplates are shown. The
-- target also has a nameplate and reports every hit twice; the copy arrives in
-- the same frame with the same values. UnitIsUnit can't tell them apart, its
-- result may be secret in combat. So a crit waits for the end of the frame,
-- and a copy from the target unit marks it as a crit on the target.
local pendingCrit;

local function QueueCrit(onTarget, event, flags, amount)
	local key = GetTime() .. event .. flags .. amount;
	if pendingCrit and pendingCrit.key == key then
		pendingCrit.onTarget = pendingCrit.onTarget or onTarget;
		return;
	end
	local crit = { key = key, onTarget = onTarget, time = GetTime() };
	pendingCrit = crit;
	C_Timer.After(0, function()
		if pendingCrit == crit then
			pendingCrit = nil;
		end
		OnCritIfMine(crit.time, crit.onTarget);
	end);
end

local function OnNamePlateCombat(unit, event, flags, amount, school)
	-- Only crits; the killing blow guess stays with the target. Hits on
	-- friendly nameplates and heals are other people's business.
	if event ~= "WOUND" or (flags ~= "CRITICAL" and flags ~= "CRUSHING") then
		return;
	end
	if not UnitCanAttack("player", unit) then
		return;
	end
	Debug(unit, event, flags, amount, "school " .. tostring(school), "CRIT");
	QueueCrit(false, event, flags, amount);
end

local function OnUnitCombat(unit, event, flags, amount, school)
	if strfind(unit, "^nameplate") then
		OnNamePlateCombat(unit, event, flags, amount, school);
		return;
	elseif unit ~= "player" and unit ~= "target" then
		return;
	end
	local critical = flags == "CRITICAL" or flags == "CRUSHING";
	if unit == "player" then
		Debug(unit, event, flags, amount, critical and "CRIT" or "");
		if event == "WOUND" then
			local maxHealth = UnitHealthMax("player");
			if critical or (maxHealth > 0 and amount >= maxHealth * db.hurtPercent / 100) then
				OnHurt();
			end
		elseif event == "HEAL" and critical then
			OnCritIfMine();
		end
		return;
	end

	if event ~= "WOUND" and event ~= "HEAL" then
		return;
	end
	if critical then
		Debug(unit, event, flags, amount, "CRIT");
		QueueCrit(true, event, flags, amount);
		return;
	end
	if event ~= "WOUND" or amount <= 0 then
		return;
	end
	-- The target's health is a secret value in combat, so a killing blow shows
	-- only through UnitIsDead (which may flip a moment after the hit), the
	-- target vanishing (the client clears it when the mob dies) or the XP
	-- message that follows a kill. Until one of them says so, the hit waits.
	-- A hit that is followed by another one did not kill.
	if pendingHit then
		Remember(pendingHit.school, pendingHit.amount);
	end
	local hit = { school = school, amount = amount, time = GetTime() };
	pendingHit = hit;
	if UnitIsDead(unit) then
		OnKillingBlow("dead now");
		return;
	end
	C_Timer.After(KILL_WINDOW, function()
		if pendingHit ~= hit then
			return;
		end
		if not UnitExists(unit) then
			OnKillingBlow("target gone");
		elseif UnitIsDead(unit) then
			OnKillingBlow("dead later");
		else
			pendingHit = nil;
			Debug(unit, event, amount, "school " .. tostring(school), "alive");
			Remember(school, amount);
		end
	end);
end

local function UpdateEvents(frame)
	if db.enabled then
		-- RegisterUnitEvent takes at most two units; nameplates come and go.
		frame:RegisterEvent("UNIT_COMBAT");
		frame:RegisterEvent("COMBAT_TEXT_UPDATE");
		frame:RegisterEvent("CHAT_MSG_COMBAT_XP_GAIN");
		frame:RegisterEvent("PLAYER_SWING");
		frame:RegisterUnitEvent("UNIT_SPELLCAST_SUCCEEDED", "player");
		frame:RegisterUnitEvent("UNIT_SPELLCAST_CHANNEL_START", "player");
		frame:RegisterUnitEvent("UNIT_SPELLCAST_CHANNEL_STOP", "player");
	else
		frame:UnregisterEvent("UNIT_COMBAT");
		frame:UnregisterEvent("COMBAT_TEXT_UPDATE");
		frame:UnregisterEvent("CHAT_MSG_COMBAT_XP_GAIN");
		frame:UnregisterEvent("PLAYER_SWING");
		frame:UnregisterEvent("UNIT_SPELLCAST_SUCCEEDED");
		frame:UnregisterEvent("UNIT_SPELLCAST_CHANNEL_START");
		frame:UnregisterEvent("UNIT_SPELLCAST_CHANNEL_STOP");
		channeling = false;
	end
end

local frame = CreateFrame("Frame");

local function RegisterOptions()
	local category = Settings.RegisterVerticalLayoutCategory("Forever UwU");

	local function Checkbox(key, label, tooltip)
		local setting = Settings.RegisterAddOnSetting(category, "FOREVER_UWU_" .. strupper(key), key,
			db, Settings.VarType.Boolean, label, DEFAULTS[key]);
		Settings.CreateCheckbox(category, setting, tooltip);
		return setting;
	end

	local function Slider(key, label, tooltip, minValue, maxValue, step, format)
		local setting = Settings.RegisterAddOnSetting(category, "FOREVER_UWU_" .. strupper(key), key,
			db, Settings.VarType.Number, label, DEFAULTS[key]);
		local options = Settings.CreateSliderOptions(minValue, maxValue, step);
		options:SetLabelFormatter(MinimalSliderWithSteppersMixin.Label.Right, function(value)
			return format:format(value);
		end);
		Settings.CreateSlider(category, setting, options, tooltip);
	end

	local enabled = Checkbox("enabled", "Enable Forever UwU", "Switches all sounds on or off.");
	enabled:SetValueChangedCallback(function()
		UpdateEvents(frame);
	end);
	Slider("volume", "Volume",
		"Volume of the uwus, on top of the game's master volume. The clips are already leveled so none is much louder than the others.",
		VOLUME_STEP, 100, VOLUME_STEP, "%d %%");
	if CreateSettingsButtonInitializer then
		Settings.RegisterInitializer(category, CreateSettingsButtonInitializer("Test sound", "Play uwu", function()
			Play("crit");
		end, "Plays one uwu at the volume above.", true));
	end

	Checkbox("bubbles", "Floating uwu text",
		"Shows a floating uwu over your character with every sound. Only you see it.");
	Slider("bubbleX", "Text position: sideways",
		"Distance of the text from the middle of the screen, where your character stands. Use the test button to check.",
		-600, 600, 10, "%d");
	Slider("bubbleY", "Text position: height",
		"Height of the text above the middle of the screen. Use the test button to check.", -400, 500, 10, "%d");

	Checkbox("crit", "UwU on my crits", "Plays a random uwu when you land a critical hit or heal.");
	Checkbox("small", "Small uwus in between",
		"When crits come faster than the cooldown below, plays short quiet uwus instead of nothing.");
	Slider("critCooldown", "Seconds between full uwus",
		"A full uwu plays at most this often; crits in between get a small uwu.", 0, 5, 0.25, "%.2f s");
	Checkbox("hurt", "Angry uwu when I get hit hard",
		"Plays an angry uwu or an ara ara when you take a critical hit or a big hit.");
	Slider("hurtPercent", "Big hit threshold",
		"A single hit that takes at least this share of your maximum health counts as big.", 5, 100, 5, "%d %%");
	Slider("hurtCooldown", "Seconds between angry uwus", "An angry uwu plays at most this often.", 0, 10, 0.5, "%.1f s");

	return category;
end

-- A page under the options with one button per clip, to hear each of them.
local BOARD_POOLS = {
	{ kind = "crit", title = "UwU on crits" },
	{ kind = "small", title = "Small uwus" },
	{ kind = "hurt", title = "Angry uwus" },
};
local BOARD_COLUMNS = 3;
local BOARD_BUTTON_WIDTH, BOARD_BUTTON_HEIGHT = 190, 22;

-- "sounds\%d\crit\cute-uwu-73482.ogg" -> "cute uwu"
local function ClipName(path)
	local name = path:match("([^\\]+)%.ogg$") or path;
	return (name:gsub("%-%d+$", ""):gsub("%-", " "));
end

local function RegisterSoundBoard(parent)
	local panel = CreateFrame("Frame");

	local title = panel:CreateFontString(nil, "ARTWORK", "GameFontHighlightHuge");
	title:SetPoint("TOPLEFT", 7, -22);
	title:SetText("Sounds");

	local scroll = CreateFrame("ScrollFrame", nil, panel, "UIPanelScrollFrameTemplate");
	scroll:SetPoint("TOPLEFT", 0, -56);
	scroll:SetPoint("BOTTOMRIGHT", -28, 8);
	local content = CreateFrame("Frame", nil, scroll);
	content:SetSize(BOARD_COLUMNS * (BOARD_BUTTON_WIDTH + 6), 1);
	scroll:SetScrollChild(content);

	local y = 0;
	for _, pool in ipairs(BOARD_POOLS) do
		local clips = {};
		for _, list in ipairs(ns.soundLists or {}) do
			for _, path in ipairs(list[pool.kind] or {}) do
				clips[#clips + 1] = { path = path, set = list.set };
			end
		end
		if #clips > 0 then
			local header = content:CreateFontString(nil, "ARTWORK", "GameFontNormalLarge");
			header:SetPoint("TOPLEFT", 10, -y);
			header:SetText(("%s (%d)"):format(pool.title, #clips));
			y = y + 26;
			for i, clip in ipairs(clips) do
				local column = (i - 1) % BOARD_COLUMNS;
				local row = math.floor((i - 1) / BOARD_COLUMNS);
				local button = CreateFrame("Button", nil, content, "UIPanelButtonTemplate");
				button:SetSize(BOARD_BUTTON_WIDTH, BOARD_BUTTON_HEIGHT);
				button:SetPoint("TOPLEFT", 10 + column * (BOARD_BUTTON_WIDTH + 6), -(y + row * (BOARD_BUTTON_HEIGHT + 4)));
				local label = ClipName(clip.path);
				if clip.set ~= "public" then
					label = label .. " (" .. clip.set .. ")";
				end
				button:SetText(label);
				local kind, path = pool.kind, clip.path;
				button:SetScript("OnClick", function()
					PlayPath(kind, path);
				end);
			end
			y = y + math.ceil(#clips / BOARD_COLUMNS) * (BOARD_BUTTON_HEIGHT + 4) + 16;
		end
	end
	content:SetHeight(math.max(y, 1));

	return Settings.RegisterCanvasLayoutSubcategory(parent, panel, "Sounds");
end

local category, soundBoard;

SLASH_FOREVERUWU1 = "/uwu";
SlashCmdList.FOREVERUWU = function(msg)
	msg = strlower(strtrim(msg or ""));
	if msg == "debug" then
		debugMode = not debugMode;
		print("|cffff80c0Forever UwU|r: debug " .. (debugMode and "on" or "off"));
	elseif msg == "crit" or msg == "hurt" or msg == "small" then
		if not Play(msg) then
			print("|cffff80c0Forever UwU|r: no " .. msg .. " sounds installed.");
		end
	elseif msg == "sounds" and soundBoard then
		Settings.OpenToCategory(soundBoard:GetID());
	elseif category then
		Settings.OpenToCategory(category:GetID());
	end
end;

frame:RegisterEvent("ADDON_LOADED");
frame:RegisterEvent("PLAYER_LOGIN");
frame:SetScript("OnEvent", function(self, event, arg1, ...)
	if event == "UNIT_COMBAT" then
		OnUnitCombat(arg1, ...);
	elseif event == "COMBAT_TEXT_UPDATE" then
		OnCombatText(arg1);
	elseif event == "CHAT_MSG_COMBAT_XP_GAIN" then
		OnKillingBlow("xp");
	elseif event == "PLAYER_SWING" then
		OnSwing(...);
	elseif event == "UNIT_SPELLCAST_SUCCEEDED" then
		lastCast = GetTime();
	elseif event == "UNIT_SPELLCAST_CHANNEL_START" then
		channeling = true;
	elseif event == "UNIT_SPELLCAST_CHANNEL_STOP" then
		-- The last tick can land after the channel ends.
		channeling = false;
		lastCast = GetTime();
	elseif event == "ADDON_LOADED" then
		if arg1 == ADDON_NAME then
			self:UnregisterEvent("ADDON_LOADED");
			ForeverUwUDB = ForeverUwUDB or {};
			db = ForeverUwUDB;
			for key, value in pairs(DEFAULTS) do
				if db[key] == nil then
					db[key] = value;
				end
			end
			-- Only the rendered levels exist as files.
			db.volume = math.min(100, math.max(VOLUME_STEP,
				math.floor(db.volume / VOLUME_STEP + 0.5) * VOLUME_STEP));
			category = RegisterOptions();
			soundBoard = RegisterSoundBoard(category);
			Settings.RegisterAddOnCategory(category);
		end
	elseif event == "PLAYER_LOGIN" then
		UpdateEvents(self);
	end
end);
