-- Plays a random uwu when the player lands a critical hit or heal, and an
-- angry uwu / ara ara when the player gets crit or loses a big chunk of health
-- in one hit. Sound lists come from Sounds.lua (and SoundsLocal.lua for clips
-- that stay on this machine); WoW can't list files, so they are generated by
-- tools/build_sounds.py.

local ADDON_NAME, ns = ...;

local DEFAULTS = {
	enabled = true,
	crit = true,
	hurt = true,
	small = true,
	critCooldown = 1.5,
	hurtCooldown = 3,
	hurtPercent = 25,
	volume = 60,
	bubbles = true,
	bubbleX = 40,
	bubbleY = 140,
};

-- PlaySoundFile has no volume argument, so tools/build_sounds.py renders every
-- clip once per level and the sound lists hold a %d for the level.
local VOLUME_STEP = 20;

-- Small uwus fill the gaps between full ones but must not stack into noise
-- when an AoE crits ten targets in the same frame.
local SMALL_GAP = 0.2;
local CHANNEL = "Master";

local db;
local lastCrit, lastSmall, lastHurt = 0, 0, 0;

-- Shuffle bag per pool: every clip plays once before any clip repeats,
-- and the last clip of a round never opens the next one.
local bags = {};

local function Pool(kind)
	local pool = {};
	for _, list in ipairs(ns.soundLists or {}) do
		for _, path in ipairs(list[kind] or {}) do
			pool[#pool + 1] = path;
		end
	end
	return pool;
end

local function NextSound(kind)
	local bag = bags[kind];
	if not bag or bag.pos > #bag then
		local pool = Pool(kind);
		if #pool == 0 then
			return nil;
		end
		for i = #pool, 2, -1 do
			local j = math.random(i);
			pool[i], pool[j] = pool[j], pool[i];
		end
		local previous = bag and bag[#bag];
		if #pool > 1 and pool[1] == previous then
			pool[1], pool[#pool] = pool[#pool], pool[1];
		end
		pool.pos = 1;
		bags[kind] = pool;
		bag = pool;
	end
	local path = bag[bag.pos];
	bag.pos = bag.pos + 1;
	return path;
end

local function Play(kind)
	if db.bubbles then
		ns.ShowBubble(kind, db.bubbleX, db.bubbleY);
	end
	local path = NextSound(kind);
	if path then
		PlaySoundFile(path:format(db.volume), CHANNEL);
		return true;
	end
	return false;
end

local function OnOwnCrit()
	if not db.crit then
		return;
	end
	local now = GetTime();
	if now - lastCrit >= db.critCooldown then
		lastCrit = now;
		lastSmall = now;
		Play("crit");
	elseif db.small and now - lastSmall >= SMALL_GAP then
		lastSmall = now;
		Play("small");
	end
end

local function OnHurt()
	if not db.hurt then
		return;
	end
	local now = GetTime();
	if now - lastHurt >= db.hurtCooldown then
		lastHurt = now;
		-- Keeps a crit uwu from talking over the hurt sound right away.
		lastCrit = now;
		Play("hurt");
	end
end

-- The combat log is off limits to addons on this client (registering
-- COMBAT_LOG_EVENT_UNFILTERED is a forbidden action), so this uses UNIT_COMBAT,
-- the event behind the hit numbers on the unit frames, plus COMBAT_TEXT_UPDATE,
-- which names crits on the player as *_CRIT. UNIT_COMBAT has no source, so a
-- crit on the target counts as the player's own while the player is in combat;
-- in a group, other players' crits on the same target count too.
--
-- A killing blow comes without the CRITICAL flag even when it crit. Mobs often
-- die after a few hits, so most crits are killing blows. For those, a hit
-- clearly above the biggest recent plain hit of its damage school counts as a
-- crit. Comparing with the biggest (not the typical) hit keeps a strong ability
-- from passing as a crit auto attack; a crit auto attack that kills is missed
-- instead. Crits do double damage, spells 1.5x. Kept across fights.
local HISTORY = 15;
local MIN_HISTORY = 3;
local CRIT_FACTOR = 1.3;
local history = {};

local function Remember(school, amount)
	local list = history[school];
	if not list then
		list = {};
		history[school] = list;
	end
	list[#list + 1] = amount;
	if #list > HISTORY then
		table.remove(list, 1);
	end
end

local function LooksLikeCrit(school, amount)
	local list = history[school];
	if not list or #list < MIN_HISTORY then
		return false;
	end
	local biggest = math.max(unpack(list));
	return biggest > 0 and amount >= biggest * CRIT_FACTOR;
end

local debugMode = false;

local function Debug(...)
	if debugMode then
		print("|cffff80c0UwU|r", ...);
	end
end

local CRIT_TEXT = {
	DAMAGE_CRIT = "hurt",
	SPELL_DAMAGE_CRIT = "hurt",
	HEAL_CRIT = "crit",
	PERIODIC_HEAL_CRIT = "crit",
};

local function OnCombatText(textType)
	local kind = CRIT_TEXT[textType];
	if kind then
		Debug("text", textType, kind);
	end
	if kind == "hurt" then
		OnHurt();
	elseif kind == "crit" then
		OnOwnCrit();
	end
end

-- The last plain hit on the target, until it is known whether it killed.
local KILL_WINDOW = 0.3;
local pendingHit;

local function OnKillingBlow(how)
	local hit = pendingHit;
	pendingHit = nil;
	if not hit then
		return;
	end
	local crit = LooksLikeCrit(hit.school, hit.amount);
	Debug("kill", hit.amount, "school " .. tostring(hit.school), how, crit and "CRIT" or "");
	if crit then
		OnOwnCrit();
	end
end

local function OnUnitCombat(unit, event, flags, amount, school)
	local critical = flags == "CRITICAL" or flags == "CRUSHING";
	if unit == "player" then
		Debug(unit, event, flags, amount, critical and "CRIT" or "");
		if event == "WOUND" then
			local maxHealth = UnitHealthMax("player");
			if critical or (maxHealth > 0 and amount >= maxHealth * db.hurtPercent / 100) then
				OnHurt();
			end
		elseif event == "HEAL" and critical then
			OnOwnCrit();
		end
		return;
	end

	if event ~= "WOUND" and event ~= "HEAL" then
		return;
	end
	if critical then
		Debug(unit, event, flags, amount, "CRIT");
		if UnitAffectingCombat("player") then
			OnOwnCrit();
		end
		return;
	end
	if event ~= "WOUND" or amount <= 0 then
		return;
	end
	-- The target's health is a secret value in combat, so a killing blow shows
	-- only through UnitIsDead (which may flip a moment after the hit), the
	-- target vanishing (the client clears it when the mob dies) or the XP
	-- message that follows a kill. Until one of them says so, the hit waits.
	-- A hit that is followed by another one did not kill.
	if pendingHit then
		Remember(pendingHit.school, pendingHit.amount);
	end
	local hit = { school = school, amount = amount };
	pendingHit = hit;
	if UnitIsDead(unit) then
		OnKillingBlow("dead now");
		return;
	end
	C_Timer.After(KILL_WINDOW, function()
		if pendingHit ~= hit then
			return;
		end
		if not UnitExists(unit) then
			OnKillingBlow("target gone");
		elseif UnitIsDead(unit) then
			OnKillingBlow("dead later");
		else
			pendingHit = nil;
			Debug(unit, event, amount, "school " .. tostring(school), "alive");
			Remember(school, amount);
		end
	end);
end

local function UpdateEvents(frame)
	if db.enabled then
		frame:RegisterUnitEvent("UNIT_COMBAT", "player", "target");
		frame:RegisterEvent("COMBAT_TEXT_UPDATE");
		frame:RegisterEvent("CHAT_MSG_COMBAT_XP_GAIN");
	else
		frame:UnregisterEvent("UNIT_COMBAT");
		frame:UnregisterEvent("COMBAT_TEXT_UPDATE");
		frame:UnregisterEvent("CHAT_MSG_COMBAT_XP_GAIN");
	end
end

local frame = CreateFrame("Frame");

local function RegisterOptions()
	local category = Settings.RegisterVerticalLayoutCategory("Forever UwU");

	local function Checkbox(key, label, tooltip)
		local setting = Settings.RegisterAddOnSetting(category, "FOREVER_UWU_" .. strupper(key), key,
			db, Settings.VarType.Boolean, label, DEFAULTS[key]);
		Settings.CreateCheckbox(category, setting, tooltip);
		return setting;
	end

	local function Slider(key, label, tooltip, minValue, maxValue, step, format)
		local setting = Settings.RegisterAddOnSetting(category, "FOREVER_UWU_" .. strupper(key), key,
			db, Settings.VarType.Number, label, DEFAULTS[key]);
		local options = Settings.CreateSliderOptions(minValue, maxValue, step);
		options:SetLabelFormatter(MinimalSliderWithSteppersMixin.Label.Right, function(value)
			return format:format(value);
		end);
		Settings.CreateSlider(category, setting, options, tooltip);
	end

	local enabled = Checkbox("enabled", "Enable Forever UwU", "Switches all sounds on or off.");
	enabled:SetValueChangedCallback(function()
		UpdateEvents(frame);
	end);
	Slider("volume", "Volume",
		"Volume of the uwus, on top of the game's master volume. The clips are already leveled so none is much louder than the others.",
		VOLUME_STEP, 100, VOLUME_STEP, "%d %%");
	if CreateSettingsButtonInitializer then
		Settings.RegisterInitializer(category, CreateSettingsButtonInitializer("Test sound", "Play uwu", function()
			Play("crit");
		end, "Plays one uwu at the volume above.", true));
	end

	Checkbox("bubbles", "Floating uwu text",
		"Shows a floating uwu over your character with every sound. Only you see it.");
	Slider("bubbleX", "Text position: sideways",
		"Distance of the text from the middle of the screen, where your character stands. Use the test button to check.",
		-600, 600, 10, "%d");
	Slider("bubbleY", "Text position: height",
		"Height of the text above the middle of the screen. Use the test button to check.", -400, 500, 10, "%d");

	Checkbox("crit", "UwU on my crits", "Plays a random uwu when you land a critical hit or heal.");
	Checkbox("small", "Small uwus in between",
		"When crits come faster than the cooldown below, plays short quiet uwus instead of nothing.");
	Slider("critCooldown", "Seconds between full uwus",
		"A full uwu plays at most this often; crits in between get a small uwu.", 0, 5, 0.25, "%.2f s");
	Checkbox("hurt", "Angry uwu when I get hit hard",
		"Plays an angry uwu or an ara ara when you take a critical hit or a big hit.");
	Slider("hurtPercent", "Big hit threshold",
		"A single hit that takes at least this share of your maximum health counts as big.", 5, 100, 5, "%d %%");
	Slider("hurtCooldown", "Seconds between angry uwus", "An angry uwu plays at most this often.", 0, 10, 0.5, "%.1f s");

	Settings.RegisterAddOnCategory(category);
	return category;
end

local category;

SLASH_FOREVERUWU1 = "/uwu";
SlashCmdList.FOREVERUWU = function(msg)
	msg = strlower(strtrim(msg or ""));
	if msg == "debug" then
		debugMode = not debugMode;
		print("|cffff80c0Forever UwU|r: debug " .. (debugMode and "on" or "off"));
	elseif msg == "crit" or msg == "hurt" or msg == "small" then
		if not Play(msg) then
			print("|cffff80c0Forever UwU|r: no " .. msg .. " sounds installed.");
		end
	elseif category then
		Settings.OpenToCategory(category:GetID());
	end
end;

frame:RegisterEvent("ADDON_LOADED");
frame:RegisterEvent("PLAYER_LOGIN");
frame:SetScript("OnEvent", function(self, event, arg1, ...)
	if event == "UNIT_COMBAT" then
		OnUnitCombat(arg1, ...);
	elseif event == "COMBAT_TEXT_UPDATE" then
		OnCombatText(arg1);
	elseif event == "CHAT_MSG_COMBAT_XP_GAIN" then
		OnKillingBlow("xp");
	elseif event == "ADDON_LOADED" then
		if arg1 == ADDON_NAME then
			self:UnregisterEvent("ADDON_LOADED");
			ForeverUwUDB = ForeverUwUDB or {};
			db = ForeverUwUDB;
			for key, value in pairs(DEFAULTS) do
				if db[key] == nil then
					db[key] = value;
				end
			end
			-- Only the rendered levels exist as files.
			db.volume = math.min(100, math.max(VOLUME_STEP,
				math.floor(db.volume / VOLUME_STEP + 0.5) * VOLUME_STEP));
			category = RegisterOptions();
		end
	elseif event == "PLAYER_LOGIN" then
		UpdateEvents(self);
	end
end);
