-- Generated by tools/build_sounds.py, don't edit by hand.
-- %d is the volume level in percent.
local _, ns = ...;
ns.soundLists = ns.soundLists or {};
ns.soundLists[#ns.soundLists + 1] = {
	set = "public",
	crit = {
		"Interface\\AddOns\\ForeverUwU\\sounds\\%d\\crit\\cute-uwu-73482.ogg",
		"Interface\\AddOns\\ForeverUwU\\sounds\\%d\\crit\\girl-uwu-43540.ogg",
		"Interface\\AddOns\\ForeverUwU\\sounds\\%d\\crit\\hewwo-19335.ogg",
		"Interface\\AddOns\\ForeverUwU\\sounds\\%d\\crit\\owo-72478.ogg",
		"Interface\\AddOns\\ForeverUwU\\sounds\\%d\\crit\\uwu-discord-gorl-36357.ogg",
	},
	hurt = {
		"Interface\\AddOns\\ForeverUwU\\sounds\\%d\\hurt\\akeno-ara-ara.ogg",
		"Interface\\AddOns\\ForeverUwU\\sounds\\%d\\hurt\\angry-anime-girl-sound-12017.ogg",
		"Interface\\AddOns\\ForeverUwU\\sounds\\%d\\hurt\\anime-girl-scream-17667.ogg",
		"Interface\\AddOns\\ForeverUwU\\sounds\\%d\\hurt\\anime-scared-girl-84264.ogg",
		"Interface\\AddOns\\ForeverUwU\\sounds\\%d\\hurt\\anta-baka.ogg",
		"Interface\\AddOns\\ForeverUwU\\sounds\\%d\\hurt\\ara-ara-shinobu-4575.ogg",
		"Interface\\AddOns\\ForeverUwU\\sounds\\%d\\hurt\\ara-ara.ogg",
		"Interface\\AddOns\\ForeverUwU\\sounds\\%d\\hurt\\baka-cirno-15655.ogg",
		"Interface\\AddOns\\ForeverUwU\\sounds\\%d\\hurt\\cute-gasp-56097.ogg",
		"Interface\\AddOns\\ForeverUwU\\sounds\\%d\\hurt\\kyaa.ogg",
		"Interface\\AddOns\\ForeverUwU\\sounds\\%d\\hurt\\polka-itai-306.ogg",
	},
	small = {
		"Interface\\AddOns\\ForeverUwU\\sounds\\%d\\small\\cute-uwu-73482.ogg",
		"Interface\\AddOns\\ForeverUwU\\sounds\\%d\\small\\girl-uwu-43540.ogg",
		"Interface\\AddOns\\ForeverUwU\\sounds\\%d\\small\\hewwo-19335.ogg",
		"Interface\\AddOns\\ForeverUwU\\sounds\\%d\\small\\owo-72478.ogg",
		"Interface\\AddOns\\ForeverUwU\\sounds\\%d\\small\\uwu-discord-gorl-36357.ogg",
	},
};
