"""Turns raw clips into the addon's .ogg files and writes the Lua sound list.

WoW can't list files in a folder, so every clip the addon may play has to be
named in a Lua file. Two sets exist:

  public  raw/public/<pool>/*  ->  sounds/<level>/<pool>/*.ogg        + Sounds.lua
  local   raw/local/<pool>/*   ->  sounds/local/<level>/<pool>/*.ogg  + SoundsLocal.lua

Pools are crit, hurt and small. The public set ships on CurseForge; the local
set (git-ignored, never packaged) holds clips that may not be redistributed.
If a set has no raw/<set>/small folder, the small uwus are derived from its
crit clips: shortened and about 12 dB quieter.

Every clip is trimmed of leading/trailing silence, made mono and loudness-
normalized, so no clip is much louder than the others, and cut to 2.5 s. PlaySoundFile has no
volume argument, so each clip is rendered once per volume level (LEVELS, in
percent) and the addon's volume slider picks the level.

Usage:  python tools/build_sounds.py [public|local ...]   (default: both)
Needs ffmpeg on PATH.
"""

import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
POOLS = ("crit", "hurt", "small")
RAW_EXT = {".wav", ".mp3", ".ogg", ".m4a", ".flac", ".webm", ".opus", ".aac"}
SETS = {
    "public": (ROOT / "raw" / "public", ROOT / "sounds", ROOT / "Sounds.lua"),
    "local": (ROOT / "raw" / "local", ROOT / "sounds" / "local", ROOT / "SoundsLocal.lua"),
}

TRIM = (
    "silenceremove=start_periods=1:start_threshold=-45dB:start_silence=0.02,"
    "areverse,silenceremove=start_periods=1:start_threshold=-45dB:start_silence=0.05,areverse"
)
NORMALIZE = "loudnorm=I=-16:TP=-1.5:LRA=11"
# A crit uwu must not ring on through the next fight: at most 2.5 s, faded out.
CAP = "atrim=0:2.5,afade=t=out:st=2.1:d=0.4"
# Small uwu: first 0.7 s, faded out, about 12 dB under a full one.
SMALL = "atrim=0:0.7,afade=t=out:st=0.5:d=0.2,volume=-12dB"
# Keep in sync with VOLUME_LEVELS in ForeverUwU.lua.
LEVELS = (20, 40, 60, 80, 100)


def ffmpeg(src, dst, filters):
    dst.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["ffmpeg", "-v", "error", "-y", "-i", str(src), "-vn", "-ac", "1", "-ar", "44100",
         "-af", filters, "-c:a", "libvorbis", "-q:a", "4", str(dst)],
        check=True,
    )


def build(name):
    raw_dir, out_dir, manifest = SETS[name]
    work = out_dir / "_full"
    for level in LEVELS:
        shutil.rmtree(out_dir / str(level), ignore_errors=True)
    shutil.rmtree(work, ignore_errors=True)

    # Full-volume masters first, then one copy per level.
    names = {}
    for pool in POOLS:
        sources = sorted(p for p in (raw_dir / pool).glob("*") if p.suffix.lower() in RAW_EXT)
        for src in sources:
            ffmpeg(src, work / pool / (src.stem + ".ogg"), f"{TRIM},{CAP},{NORMALIZE}")
        names[pool] = [src.stem + ".ogg" for src in sources]
    if not names["small"]:
        for clip in names["crit"]:
            ffmpeg(work / "crit" / clip, work / "small" / clip, SMALL)
        names["small"] = list(names["crit"])

    for level in LEVELS:
        for pool in POOLS:
            for clip in names[pool]:
                ffmpeg(work / pool / clip, out_dir / str(level) / pool / clip, f"volume={level / 100:.2f}")
    shutil.rmtree(work, ignore_errors=True)

    # Lua strings need doubled backslashes: Interface\AddOns\...
    parts = ["Interface", "AddOns", "ForeverUwU", *out_dir.relative_to(ROOT).parts, "%d"]
    base = "\\\\".join(parts)
    lines = [
        "-- Generated by tools/build_sounds.py, don't edit by hand.",
        "-- %d is the volume level in percent.",
        "local _, ns = ...;",
        "ns.soundLists = ns.soundLists or {};",
        "ns.soundLists[#ns.soundLists + 1] = {",
        f'	set = "{name}",',
    ]
    for pool in POOLS:
        lines.append(f"\t{pool} = {{")
        for clip in sorted(names[pool]):
            lines.append(f'\t\t"{base}\\\\{pool}\\\\{clip}",')
        lines.append("\t},")
    lines.append("};")
    manifest.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"{name}: " + ", ".join(f"{len(names[p])} {p}" for p in POOLS) + f" x {len(LEVELS)} levels")


if __name__ == "__main__":
    for name in sys.argv[1:] or SETS:
        build(name)
